name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3


    - name: Install CMake & Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.25.0"
        ninjaVersion: "^1.10.1"

    - name: Configure
      run: >
        cmake -S ${{github.workspace}}
        -B ${{github.workspace}}/build
        -G Ninja
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_COLOR_DIAGNOSTICS=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose
